appearance: # view
  theme: system # system | light | dark
  layout:
    sidebar: 
      is visible: true
    title bar: 
      is visible: true
behavior:
  will sync input to url: false
  will persist input: false
  will pipe output to new command: false
shortcuts:
  toggle sidebar: ctrl+b
  # toggle arguments: ctrl+shift+a
  # toggle recipe/program/logics/flow: ctrl+shift+r ctrl+shift+p ctrl+shift+l ctrl+shift+f
  # toggle input: ctrl+shift+i
  # toggle output: ctrl+shift+o
  open command palette: ctrl+shift+p ctrl+p ctrl+f ctrl+k
  open settings: ctrl+,
  open shortcuts: ctrl+?
navigation:
  page: home # home | tool
  tool: '' # '' | a tool
