// Element data
const elements = [
  // Period 1
  {
    number: 1,
    symbol: "H",
    name: { en: "Hydrogen", ja: "水素", zh: "氢" },
    electron: "1s¹",
    group: 1,
    period: 1,
    category: "Reactive Nonmetal",
    mass: "1.008",
    electronegativity: 2.2,
    melting: 13.99,
    boiling: 20.271,
  },
  {
    number: 2,
    symbol: "He",
    name: { en: "Helium", ja: "ヘリウム", zh: "氦" },
    electron: "1s²",
    group: 18,
    period: 1,
    category: "Noble Gas",
    mass: "4.0026",
    electronegativity: null,
    melting: 0.95,
    boiling: 4.222,
  },

  // Period 2
  {
    number: 3,
    symbol: "Li",
    name: { en: "Lithium", ja: "リチウム", zh: "锂" },
    electron: "2s¹",
    group: 1,
    period: 2,
    category: "Alkali Metal",
    mass: "6.94",
    electronegativity: 0.98,
    melting: 453.65,
    boiling: 1603,
  },
  {
    number: 4,
    symbol: "Be",
    name: { en: "Beryllium", ja: "ベリリウム", zh: "铍" },
    electron: "2s²",
    group: 2,
    period: 2,
    category: "Alkaline Earth Metal",
    mass: "9.0122",
    electronegativity: 1.57,
    melting: 1560,
    boiling: 2742,
  },
  {
    number: 5,
    symbol: "B",
    name: { en: "Boron", ja: "ホウ素", zh: "硼" },
    electron: "2s² 2p¹",
    group: 13,
    period: 2,
    category: "Metalloid",
    mass: "10.81",
    electronegativity: 2.04,
    melting: 2349,
    boiling: 4200,
  },
  {
    number: 6,
    symbol: "C",
    name: { en: "Carbon", ja: "炭素", zh: "碳" },
    electron: "2s² 2p²",
    group: 14,
    period: 2,
    category: "Reactive Nonmetal",
    mass: "12.011",
    electronegativity: 2.55,
    melting: 3800,
    boiling: 4300,
  },
  {
    number: 7,
    symbol: "N",
    name: { en: "Nitrogen", ja: "窒素", zh: "氮" },
    electron: "2s² 2p³",
    group: 15,
    period: 2,
    category: "Reactive Nonmetal",
    mass: "14.007",
    electronegativity: 3.04,
    melting: 63.15,
    boiling: 77.36,
  },
  {
    number: 8,
    symbol: "O",
    name: { en: "Oxygen", ja: "酸素", zh: "氧" },
    electron: "2s² 2p⁴",
    group: 16,
    period: 2,
    category: "Reactive Nonmetal",
    mass: "15.999",
    electronegativity: 3.44,
    melting: 54.36,
    boiling: 90.188,
  },
  {
    number: 9,
    symbol: "F",
    name: { en: "Fluorine", ja: "フッ素", zh: "氟" },
    electron: "2s² 2p⁵",
    group: 17,
    period: 2,
    category: "Reactive Nonmetal",
    mass: "18.998",
    electronegativity: 3.98,
    melting: 53.48,
    boiling: 85.03,
  },
  {
    number: 10,
    symbol: "Ne",
    name: { en: "Neon", ja: "ネオン", zh: "氖" },
    electron: "2s² 2p⁶",
    group: 18,
    period: 2,
    category: "Noble Gas",
    mass: "20.180",
    electronegativity: null,
    melting: 24.56,
    boiling: 27.07,
  },

  // Period 3
  {
    number: 11,
    symbol: "Na",
    name: { en: "Sodium", ja: "ナトリウム", zh: "钠" },
    electron: "3s¹",
    group: 1,
    period: 3,
    category: "Alkali Metal",
    mass: "22.990",
    electronegativity: 0.93,
    melting: 370.87,
    boiling: 1156,
  },
  {
    number: 12,
    symbol: "Mg",
    name: { en: "Magnesium", ja: "マグネシウム", zh: "镁" },
    electron: "3s²",
    group: 2,
    period: 3,
    category: "Alkaline Earth Metal",
    mass: "24.305",
    electronegativity: 1.31,
    melting: 923,
    boiling: 1363,
  },
  {
    number: 13,
    symbol: "Al",
    name: { en: "Aluminum", ja: "アルミニウム", zh: "铝" },
    electron: "3s² 3p¹",
    group: 13,
    period: 3,
    category: "Post-transition Metal",
    mass: "26.982",
    electronegativity: 1.61,
    melting: 933.47,
    boiling: 2792,
  },
  {
    number: 14,
    symbol: "Si",
    name: { en: "Silicon", ja: "ケイ素", zh: "硅" },
    electron: "3s² 3p²",
    group: 14,
    period: 3,
    category: "Metalloid",
    mass: "28.085",
    electronegativity: 1.9,
    melting: 1687,
    boiling: 3538,
  },
  {
    number: 15,
    symbol: "P",
    name: { en: "Phosphorus", ja: "リン", zh: "磷" },
    electron: "3s² 3p³",
    group: 15,
    period: 3,
    category: "Reactive Nonmetal",
    mass: "30.974",
    electronegativity: 2.19,
    melting: 317.3,
    boiling: 553.6,
  },
  {
    number: 16,
    symbol: "S",
    name: { en: "Sulfur", ja: "硫黄", zh: "硫" },
    electron: "3s² 3p⁴",
    group: 16,
    period: 3,
    category: "Reactive Nonmetal",
    mass: "32.06",
    electronegativity: 2.58,
    melting: 388.36,
    boiling: 717.8,
  },
  {
    number: 17,
    symbol: "Cl",
    name: { en: "Chlorine", ja: "塩素", zh: "氯" },
    electron: "3s² 3p⁵",
    group: 17,
    period: 3,
    category: "Reactive Nonmetal",
    mass: "35.45",
    electronegativity: 3.16,
    melting: 171.6,
    boiling: 239.11,
  },
  {
    number: 18,
    symbol: "Ar",
    name: { en: "Argon", ja: "アルゴン", zh: "氩" },
    electron: "3s² 3p⁶",
    group: 18,
    period: 3,
    category: "Noble Gas",
    mass: "39.95",
    electronegativity: null,
    melting: 83.8,
    boiling: 87.3,
  },

  // Period 4
  {
    number: 19,
    symbol: "K",
    name: { en: "Potassium", ja: "カリウム", zh: "钾" },
    electron: "4s¹",
    group: 1,
    period: 4,
    category: "Alkali Metal",
    mass: "39.098",
    electronegativity: 0.82,
    melting: 336.53,
    boiling: 1032,
  },
  {
    number: 20,
    symbol: "Ca",
    name: { en: "Calcium", ja: "カルシウム", zh: "钙" },
    electron: "4s²",
    group: 2,
    period: 4,
    category: "Alkaline Earth Metal",
    mass: "40.078",
    electronegativity: 1.0,
    melting: 1115,
    boiling: 1757,
  },
  {
    number: 21,
    symbol: "Sc",
    name: { en: "Scandium", ja: "スカンジウム", zh: "钪" },
    electron: "3d¹ 4s²",
    group: 3,
    period: 4,
    category: "Transition Metal",
    mass: "44.956",
    electronegativity: 1.36,
    melting: 1814,
    boiling: 3109,
  },
  {
    number: 22,
    symbol: "Ti",
    name: { en: "Titanium", ja: "チタン", zh: "钛" },
    electron: "3d² 4s²",
    group: 4,
    period: 4,
    category: "Transition Metal",
    mass: "47.867",
    electronegativity: 1.54,
    melting: 1941,
    boiling: 3560,
  },
  {
    number: 23,
    symbol: "V",
    name: { en: "Vanadium", ja: "バナジウム", zh: "钒" },
    electron: "3d³ 4s²",
    group: 5,
    period: 4,
    category: "Transition Metal",
    mass: "50.942",
    electronegativity: 1.63,
    melting: 2183,
    boiling: 3680,
  },
  {
    number: 24,
    symbol: "Cr",
    name: { en: "Chromium", ja: "クロム", zh: "铬" },
    electron: "3d⁵ 4s¹",
    group: 6,
    period: 4,
    category: "Transition Metal",
    mass: "51.996",
    electronegativity: 1.66,
    melting: 2180,
    boiling: 2944,
  },
  {
    number: 25,
    symbol: "Mn",
    name: { en: "Manganese", ja: "マンガン", zh: "锰" },
    electron: "3d⁵ 4s²",
    group: 7,
    period: 4,
    category: "Transition Metal",
    mass: "54.938",
    electronegativity: 1.55,
    melting: 1519,
    boiling: 2334,
  },
  {
    number: 26,
    symbol: "Fe",
    name: { en: "Iron", ja: "鉄", zh: "铁" },
    electron: "3d⁶ 4s²",
    group: 8,
    period: 4,
    category: "Transition Metal",
    mass: "55.845",
    electronegativity: 1.83,
    melting: 1811,
    boiling: 3134,
  },
  {
    number: 27,
    symbol: "Co",
    name: { en: "Cobalt", ja: "コバルト", zh: "钴" },
    electron: "3d⁷ 4s²",
    group: 9,
    period: 4,
    category: "Transition Metal",
    mass: "58.933",
    electronegativity: 1.88,
    melting: 1768,
    boiling: 3200,
  },
  {
    number: 28,
    symbol: "Ni",
    name: { en: "Nickel", ja: "ニッケル", zh: "镍" },
    electron: "3d⁸ 4s²",
    group: 10,
    period: 4,
    category: "Transition Metal",
    mass: "58.693",
    electronegativity: 1.91,
    melting: 1728,
    boiling: 3186,
  },
  {
    number: 29,
    symbol: "Cu",
    name: { en: "Copper", ja: "銅", zh: "铜" },
    electron: "3d¹⁰ 4s¹",
    group: 11,
    period: 4,
    category: "Transition Metal",
    mass: "63.546",
    electronegativity: 1.9,
    melting: 1357.77,
    boiling: 2835,
  },
  {
    number: 30,
    symbol: "Zn",
    name: { en: "Zinc", ja: "亜鉛", zh: "锌" },
    electron: "3d¹⁰ 4s²",
    group: 12,
    period: 4,
    category: "Transition Metal",
    mass: "65.38",
    electronegativity: 1.65,
    melting: 692.68,
    boiling: 1180,
  },
  {
    number: 31,
    symbol: "Ga",
    name: { en: "Gallium", ja: "ガリウム", zh: "镓" },
    electron: "3d¹⁰ 4s² 4p¹",
    group: 13,
    period: 4,
    category: "Post-transition Metal",
    mass: "69.723",
    electronegativity: 1.81,
    melting: 302.91,
    boiling: 2673,
  },
  {
    number: 32,
    symbol: "Ge",
    name: { en: "Germanium", ja: "ゲルマニウム", zh: "锗" },
    electron: "3d¹⁰ 4s² 4p²",
    group: 14,
    period: 4,
    category: "Metalloid",
    mass: "72.630",
    electronegativity: 2.01,
    melting: 1211.4,
    boiling: 3106,
  },
  {
    number: 33,
    symbol: "As",
    name: { en: "Arsenic", ja: "ヒ素", zh: "砷" },
    electron: "3d¹⁰ 4s² 4p³",
    group: 15,
    period: 4,
    category: "Metalloid",
    mass: "74.922",
    electronegativity: 2.18,
    melting: 1090,
    boiling: 887,
  },
  {
    number: 34,
    symbol: "Se",
    name: { en: "Selenium", ja: "セレン", zh: "硒" },
    electron: "3d¹⁰ 4s² 4p⁴",
    group: 16,
    period: 4,
    category: "Reactive Nonmetal",
    mass: "78.971",
    electronegativity: 2.55,
    melting: 494,
    boiling: 958,
  },
  {
    number: 35,
    symbol: "Br",
    name: { en: "Bromine", ja: "臭素", zh: "溴" },
    electron: "3d¹⁰ 4s² 4p⁵",
    group: 17,
    period: 4,
    category: "Reactive Nonmetal",
    mass: "79.904",
    electronegativity: 2.96,
    melting: 265.8,
    boiling: 332.0,
  },
  {
    number: 36,
    symbol: "Kr",
    name: { en: "Krypton", ja: "クリプトン", zh: "氪" },
    electron: "3d¹⁰ 4s² 4p⁶",
    group: 18,
    period: 4,
    category: "Noble Gas",
    mass: "83.798",
    electronegativity: 3.0,
    melting: 115.79,
    boiling: 119.93,
  },

  // Period 5
  {
    number: 37,
    symbol: "Rb",
    name: { en: "Rubidium", ja: "ルビジウム", zh: "铷" },
    electron: "5s¹",
    group: 1,
    period: 5,
    category: "Alkali Metal",
    mass: "85.468",
    electronegativity: 0.82,
    melting: 312.46,
    boiling: 961,
  },
  {
    number: 38,
    symbol: "Sr",
    name: { en: "Strontium", ja: "ストロンチウム", zh: "锶" },
    electron: "5s²",
    group: 2,
    period: 5,
    category: "Alkaline Earth Metal",
    mass: "87.62",
    electronegativity: 0.95,
    melting: 1050,
    boiling: 1655,
  },
  {
    number: 39,
    symbol: "Y",
    name: { en: "Yttrium", ja: "イットリウム", zh: "钇" },
    electron: "4d¹ 5s²",
    group: 3,
    period: 5,
    category: "Transition Metal",
    mass: "88.906",
    electronegativity: 1.22,
    melting: 1799,
    boiling: 3609,
  },
  {
    number: 40,
    symbol: "Zr",
    name: { en: "Zirconium", ja: "ジルコニウム", zh: "锆" },
    electron: "4d² 5s²",
    group: 4,
    period: 5,
    category: "Transition Metal",
    mass: "91.224",
    electronegativity: 1.33,
    melting: 2128,
    boiling: 4682,
  },
  {
    number: 41,
    symbol: "Nb",
    name: { en: "Niobium", ja: "ニオブ", zh: "铌" },
    electron: "4d⁴ 5s¹",
    group: 5,
    period: 5,
    category: "Transition Metal",
    mass: "92.906",
    electronegativity: 1.6,
    melting: 2750,
    boiling: 5017,
  },
  {
    number: 42,
    symbol: "Mo",
    name: { en: "Molybdenum", ja: "モリブデン", zh: "钼" },
    electron: "4d⁵ 5s¹",
    group: 6,
    period: 5,
    category: "Transition Metal",
    mass: "95.95",
    electronegativity: 2.16,
    melting: 2896,
    boiling: 4912,
  },
  {
    number: 43,
    symbol: "Tc",
    name: { en: "Technetium", ja: "テクネチウム", zh: "锝" },
    electron: "4d⁵ 5s²",
    group: 7,
    period: 5,
    category: "Transition Metal",
    mass: "(98)",
    electronegativity: 1.9,
    melting: 2430,
    boiling: 4538,
  },
  {
    number: 44,
    symbol: "Ru",
    name: { en: "Ruthenium", ja: "ルテニウム", zh: "钌" },
    electron: "4d⁷ 5s¹",
    group: 8,
    period: 5,
    category: "Transition Metal",
    mass: "101.07",
    electronegativity: 2.2,
    melting: 2607,
    boiling: 4423,
  },
  {
    number: 45,
    symbol: "Rh",
    name: { en: "Rhodium", ja: "ロジウム", zh: "铑" },
    electron: "4d⁸ 5s¹",
    group: 9,
    period: 5,
    category: "Transition Metal",
    mass: "102.91",
    electronegativity: 2.28,
    melting: 2237,
    boiling: 3968,
  },
  {
    number: 46,
    symbol: "Pd",
    name: { en: "Palladium", ja: "パラジウム", zh: "钯" },
    electron: "4d¹⁰",
    group: 10,
    period: 5,
    category: "Transition Metal",
    mass: "106.42",
    electronegativity: 2.2,
    melting: 1828.05,
    boiling: 3236,
  },
  {
    number: 47,
    symbol: "Ag",
    name: { en: "Silver", ja: "銀", zh: "银" },
    electron: "4d¹⁰ 5s¹",
    group: 11,
    period: 5,
    category: "Transition Metal",
    mass: "107.87",
    electronegativity: 1.93,
    melting: 1234.93,
    boiling: 2435,
  },
  {
    number: 48,
    symbol: "Cd",
    name: { en: "Cadmium", ja: "カドミウム", zh: "镉" },
    electron: "4d¹⁰ 5s²",
    group: 12,
    period: 5,
    category: "Transition Metal",
    mass: "112.41",
    electronegativity: 1.69,
    melting: 594.22,
    boiling: 1040,
  },
  {
    number: 49,
    symbol: "In",
    name: { en: "Indium", ja: "インジウム", zh: "铟" },
    electron: "4d¹⁰ 5s² 5p¹",
    group: 13,
    period: 5,
    category: "Post-transition Metal",
    mass: "114.82",
    electronegativity: 1.78,
    melting: 429.75,
    boiling: 2345,
  },
  {
    number: 50,
    symbol: "Sn",
    name: { en: "Tin", ja: "錫", zh: "锡" },
    electron: "4d¹⁰ 5s² 5p²",
    group: 14,
    period: 5,
    category: "Post-transition Metal",
    mass: "118.71",
    electronegativity: 1.96,
    melting: 505.08,
    boiling: 2875,
  },
  {
    number: 51,
    symbol: "Sb",
    name: { en: "Antimony", ja: "アンチモン", zh: "锑" },
    electron: "4d¹⁰ 5s² 5p³",
    group: 15,
    period: 5,
    category: "Metalloid",
    mass: "121.76",
    electronegativity: 2.05,
    melting: 903.78,
    boiling: 1860,
  },
  {
    number: 52,
    symbol: "Te",
    name: { en: "Tellurium", ja: "テルル", zh: "碲" },
    electron: "4d¹⁰ 5s² 5p⁴",
    group: 16,
    period: 5,
    category: "Metalloid",
    mass: "127.60",
    electronegativity: 2.1,
    melting: 722.66,
    boiling: 1261,
  },
  {
    number: 53,
    symbol: "I",
    name: { en: "Iodine", ja: "ヨウ素", zh: "碘" },
    electron: "4d¹⁰ 5s² 5p⁵",
    group: 17,
    period: 5,
    category: "Reactive Nonmetal",
    mass: "126.90",
    electronegativity: 2.66,
    melting: 386.85,
    boiling: 457.4,
  },
  {
    number: 54,
    symbol: "Xe",
    name: { en: "Xenon", ja: "キセノン", zh: "氙" },
    electron: "4d¹⁰ 5s² 5p⁶",
    group: 18,
    period: 5,
    category: "Noble Gas",
    mass: "131.29",
    electronegativity: 2.6,
    melting: 161.4,
    boiling: 165.1,
  },

  // Period 6
  {
    number: 55,
    symbol: "Cs",
    name: { en: "Cesium", ja: "セシウム", zh: "铯" },
    electron: "6s¹",
    group: 1,
    period: 6,
    category: "Alkali Metal",
    mass: "132.91",
    electronegativity: 0.79,
    melting: 301.59,
    boiling: 944,
  },
  {
    number: 56,
    symbol: "Ba",
    name: { en: "Barium", ja: "バリウム", zh: "钡" },
    electron: "6s²",
    group: 2,
    period: 6,
    category: "Alkaline Earth Metal",
    mass: "137.33",
    electronegativity: 0.89,
    melting: 1000,
    boiling: 2170,
  },
  {
    number: 57,
    symbol: "La",
    name: { en: "Lanthanum", ja: "ランタン", zh: "镧" },
    electron: "5d¹ 6s²",
    group: 3,
    period: 6,
    category: "Lanthanide",
    mass: "138.91",
    electronegativity: 1.1,
    melting: 1193,
    boiling: 3737,
  },
  {
    number: 72,
    symbol: "Hf",
    name: { en: "Hafnium", ja: "ハフニウム", zh: "铪" },
    electron: "4f¹⁴ 5d² 6s²",
    group: 4,
    period: 6,
    category: "Transition Metal",
    mass: "178.49",
    electronegativity: 1.3,
    melting: 2506,
    boiling: 4876,
  },
  {
    number: 73,
    symbol: "Ta",
    name: { en: "Tantalum", ja: "タンタル", zh: "钽" },
    electron: "4f¹⁴ 5d³ 6s²",
    group: 5,
    period: 6,
    category: "Transition Metal",
    mass: "180.95",
    electronegativity: 1.5,
    melting: 3290,
    boiling: 5731,
  },
  {
    number: 74,
    symbol: "W",
    name: { en: "Tungsten", ja: "タングステン", zh: "钨" },
    electron: "4f¹⁴ 5d⁴ 6s²",
    group: 6,
    period: 6,
    category: "Transition Metal",
    mass: "183.84",
    electronegativity: 2.36,
    melting: 3695,
    boiling: 6203,
  },
  {
    number: 75,
    symbol: "Re",
    name: { en: "Rhenium", ja: "レニウム", zh: "铼" },
    electron: "4f¹⁴ 5d⁵ 6s²",
    group: 7,
    period: 6,
    category: "Transition Metal",
    mass: "186.21",
    electronegativity: 1.9,
    melting: 3459,
    boiling: 5869,
  },
  {
    number: 76,
    symbol: "Os",
    name: { en: "Osmium", ja: "オスミウム", zh: "锇" },
    electron: "4f¹⁴ 5d⁶ 6s²",
    group: 8,
    period: 6,
    category: "Transition Metal",
    mass: "190.23",
    electronegativity: 2.2,
    melting: 3306,
    boiling: 5285,
  },
  {
    number: 77,
    symbol: "Ir",
    name: { en: "Iridium", ja: "イリジウム", zh: "铱" },
    electron: "4f¹⁴ 5d⁷ 6s²",
    group: 9,
    period: 6,
    category: "Transition Metal",
    mass: "192.22",
    electronegativity: 2.2,
    melting: 2719,
    boiling: 4701,
  },
  {
    number: 78,
    symbol: "Pt",
    name: { en: "Platinum", ja: "白金", zh: "铂" },
    electron: "4f¹⁴ 5d⁹ 6s¹",
    group: 10,
    period: 6,
    category: "Transition Metal",
    mass: "195.08",
    electronegativity: 2.28,
    melting: 2041.4,
    boiling: 4098,
  },
  {
    number: 79,
    symbol: "Au",
    name: { en: "Gold", ja: "金", zh: "金" },
    electron: "4f¹⁴ 5d¹⁰ 6s¹",
    group: 11,
    period: 6,
    category: "Transition Metal",
    mass: "196.97",
    electronegativity: 2.54,
    melting: 1337.33,
    boiling: 3129,
  },
  {
    number: 80,
    symbol: "Hg",
    name: { en: "Mercury", ja: "水銀", zh: "汞" },
    electron: "4f¹⁴ 5d¹⁰ 6s²",
    group: 12,
    period: 6,
    category: "Transition Metal",
    mass: "200.59",
    electronegativity: 2.0,
    melting: 234.32,
    boiling: 629.88,
  },
  {
    number: 81,
    symbol: "Tl",
    name: { en: "Thallium", ja: "タリウム", zh: "铊" },
    electron: "4f¹⁴ 5d¹⁰ 6s² 6p¹",
    group: 13,
    period: 6,
    category: "Post-transition Metal",
    mass: "204.38",
    electronegativity: 1.62,
    melting: 577,
    boiling: 1746,
  },
  {
    number: 82,
    symbol: "Pb",
    name: { en: "Lead", ja: "鉛", zh: "铅" },
    electron: "4f¹⁴ 5d¹⁰ 6s² 6p²",
    group: 14,
    period: 6,
    category: "Post-transition Metal",
    mass: "207.2",
    electronegativity: 1.87,
    melting: 600.61,
    boiling: 2022,
  },
  {
    number: 83,
    symbol: "Bi",
    name: { en: "Bismuth", ja: "ビスマス", zh: "铋" },
    electron: "4f¹⁴ 5d¹⁰ 6s² 6p³",
    group: 15,
    period: 6,
    category: "Post-transition Metal",
    mass: "208.98",
    electronegativity: 2.02,
    melting: 544.7,
    boiling: 1837,
  },
  {
    number: 84,
    symbol: "Po",
    name: { en: "Polonium", ja: "ポロニウム", zh: "钋" },
    electron: "4f¹⁴ 5d¹⁰ 6s² 6p⁴",
    group: 16,
    period: 6,
    category: "Post-transition Metal",
    mass: "(209)",
    electronegativity: 2.0,
    melting: 527,
    boiling: 1235,
  },
  {
    number: 85,
    symbol: "At",
    name: { en: "Astatine", ja: "アスタチン", zh: "砹" },
    electron: "4f¹⁴ 5d¹⁰ 6s² 6p⁵",
    group: 17,
    period: 6,
    category: "Metalloid",
    mass: "(210)",
    electronegativity: 2.2,
    melting: 575,
    boiling: 610,
  },
  {
    number: 86,
    symbol: "Rn",
    name: { en: "Radon", ja: "ラドン", zh: "氡" },
    electron: "4f¹⁴ 5d¹⁰ 6s² 6p⁶",
    group: 18,
    period: 6,
    category: "Noble Gas",
    mass: "(222)",
    electronegativity: 2.2,
    melting: 202,
    boiling: 211.3,
  },

  // Period 7
  {
    number: 87,
    symbol: "Fr",
    name: { en: "Francium", ja: "フランシウム", zh: "钫" },
    electron: "7s¹",
    group: 1,
    period: 7,
    category: "Alkali Metal",
    mass: "(223)",
    electronegativity: 0.7,
    melting: 300,
    boiling: 950,
  },
  {
    number: 88,
    symbol: "Ra",
    name: { en: "Radium", ja: "ラジウム", zh: "镭" },
    electron: "7s²",
    group: 2,
    period: 7,
    category: "Alkaline Earth Metal",
    mass: "(226)",
    electronegativity: 0.9,
    melting: 973,
    boiling: 2010,
  },
  {
    number: 89,
    symbol: "Ac",
    name: { en: "Actinium", ja: "アクチニウム", zh: "锕" },
    electron: "6d¹ 7s²",
    group: 3,
    period: 7,
    category: "Actinide",
    mass: "(227)",
    electronegativity: 1.1,
    melting: 1323,
    boiling: 3471,
  },
  {
    number: 104,
    symbol: "Rf",
    name: { en: "Rutherfordium", ja: "ラザホージウム", zh: "鑪" },
    electron: "5f¹⁴ 6d² 7s²",
    group: 4,
    period: 7,
    category: "Transition Metal",
    mass: "(267)",
    electronegativity: null,
    melting: 2400,
    boiling: 5800,
  },
  {
    number: 105,
    symbol: "Db",
    name: { en: "Dubnium", ja: "ドブニウム", zh: "𨧀" },
    electron: "5f¹⁴ 6d³ 7s²",
    group: 5,
    period: 7,
    category: "Transition Metal",
    mass: "(268)",
    electronegativity: null,
    melting: 2400,
    boiling: 5800,
  },
  {
    number: 106,
    symbol: "Sg",
    name: { en: "Seaborgium", ja: "シーボーギウム", zh: "𨭎" },
    electron: "5f¹⁴ 6d⁴ 7s²",
    group: 6,
    period: 7,
    category: "Transition Metal",
    mass: "(269)",
    electronegativity: null,
    melting: 2400,
    boiling: 5800,
  },
  {
    number: 107,
    symbol: "Bh",
    name: { en: "Bohrium", ja: "ボーリウム", zh: "𨨏" },
    electron: "5f¹⁴ 6d⁵ 7s²",
    group: 7,
    period: 7,
    category: "Transition Metal",
    mass: "(270)",
    electronegativity: null,
    melting: 2400,
    boiling: 5800,
  },
  {
    number: 108,
    symbol: "Hs",
    name: { en: "Hassium", ja: "ハッシウム", zh: "𨭆" },
    electron: "5f¹⁴ 6d⁶ 7s²",
    group: 8,
    period: 7,
    category: "Transition Metal",
    mass: "(269)",
    electronegativity: null,
    melting: 2400,
    boiling: 5800,
  },
  {
    number: 109,
    symbol: "Mt",
    name: { en: "Meitnerium", ja: "マイトネリウム", zh: "䥑" },
    electron: "5f¹⁴ 6d⁷ 7s²",
    group: 9,
    period: 7,
    category: "Transition Metal",
    mass: "(278)",
    electronegativity: null,
    melting: 2400,
    boiling: 5800,
  },
  {
    number: 110,
    symbol: "Ds",
    name: { en: "Darmstadtium", ja: "ダームスタチウム", zh: "鐽" },
    electron: "5f¹⁴ 6d⁹ 7s¹",
    group: 10,
    period: 7,
    category: "Transition Metal",
    mass: "(281)",
    electronegativity: null,
    melting: 2400,
    boiling: 5800,
  },
  {
    number: 111,
    symbol: "Rg",
    name: { en: "Roentgenium", ja: "レントゲニウム", zh: "錀" },
    electron: "5f¹⁴ 6d¹⁰ 7s¹",
    group: 11,
    period: 7,
    category: "Transition Metal",
    mass: "(282)",
    electronegativity: null,
    melting: 2400,
    boiling: 5800,
  },
  {
    number: 112,
    symbol: "Cn",
    name: { en: "Copernicium", ja: "コペルニシウム", zh: "鎶" },
    electron: "5f¹⁴ 6d¹⁰ 7s²",
    group: 12,
    period: 7,
    category: "Transition Metal",
    mass: "(285)",
    electronegativity: null,
    melting: 2400,
    boiling: 5800,
  },
  {
    number: 113,
    symbol: "Nh",
    name: { en: "Nihonium", ja: "ニホニウム", zh: "鉨" },
    electron: "5f¹⁴ 6d¹⁰ 7s² 7p¹",
    group: 13,
    period: 7,
    category: "Post-transition Metal",
    mass: "(286)",
    electronegativity: null,
    melting: 700,
    boiling: 1400,
  },
  {
    number: 114,
    symbol: "Fl",
    name: { en: "Flerovium", ja: "フレロビウム", zh: "鈇" },
    electron: "5f¹⁴ 6d¹⁰ 7s² 7p²",
    group: 14,
    period: 7,
    category: "Post-transition Metal",
    mass: "(289)",
    electronegativity: null,
    melting: 340,
    boiling: 420,
  },
  {
    number: 115,
    symbol: "Mc",
    name: { en: "Moscovium", ja: "モスコビウム", zh: "鏌" },
    electron: "5f¹⁴ 6d¹⁰ 7s² 7p³",
    group: 15,
    period: 7,
    category: "Post-transition Metal",
    mass: "(290)",
    electronegativity: null,
    melting: 700,
    boiling: 1400,
  },
  {
    number: 116,
    symbol: "Lv",
    name: { en: "Livermorium", ja: "リバモリウム", zh: "鉝" },
    electron: "5f¹⁴ 6d¹⁰ 7s² 7p⁴",
    group: 16,
    period: 7,
    category: "Post-transition Metal",
    mass: "(293)",
    electronegativity: null,
    melting: 700,
    boiling: 1100,
  },
  {
    number: 117,
    symbol: "Ts",
    name: { en: "Tennessine", ja: "テネシン", zh: "鿬" },
    electron: "5f¹⁴ 6d¹⁰ 7s² 7p⁵",
    group: 17,
    period: 7,
    category: "Reactive Nonmetal",
    mass: "(294)",
    electronegativity: null,
    melting: 700,
    boiling: 883,
  },
  {
    number: 118,
    symbol: "Og",
    name: { en: "Oganesson", ja: "オガネソン", zh: "鿫" },
    electron: "5f¹⁴ 6d¹⁰ 7s² 7p⁶",
    group: 18,
    period: 7,
    category: "Noble Gas",
    mass: "(294)",
    electronegativity: null,
    melting: 320,
    boiling: 350,
  },

  // Add these to your elements array - PLACE THEM IN THE APPROPRIATE POSITIONS
  {
    number: 58,
    symbol: "Ce",
    name: { en: "Cerium", ja: "セリウム", zh: "铈" },
    electron: "4f¹ 5d¹ 6s²",
    group: 3,
    period: 6,
    category: "Lanthanide",
    mass: "140.12",
    electronegativity: 1.12,
    melting: 1068,
    boiling: 3716,
  },
  {
    number: 59,
    symbol: "Pr",
    name: { en: "Praseodymium", ja: "プラセオジム", zh: "镨" },
    electron: "4f³ 6s²",
    group: 3,
    period: 6,
    category: "Lanthanide",
    mass: "140.91",
    electronegativity: 1.13,
    melting: 1208,
    boiling: 3793,
  },
  {
    number: 60,
    symbol: "Nd",
    name: { en: "Neodymium", ja: "ネオジム", zh: "钕" },
    electron: "4f⁴ 6s²",
    group: 3,
    period: 6,
    category: "Lanthanide",
    mass: "144.24",
    electronegativity: 1.14,
    melting: 1297,
    boiling: 3347,
  },
  {
    number: 61,
    symbol: "Pm",
    name: { en: "Promethium", ja: "プロメチウム", zh: "钷" },
    electron: "4f⁵ 6s²",
    group: 3,
    period: 6,
    category: "Lanthanide",
    mass: "(145)",
    electronegativity: 1.13,
    melting: 1373,
    boiling: 3273,
  },
  {
    number: 62,
    symbol: "Sm",
    name: { en: "Samarium", ja: "サマリウム", zh: "钐" },
    electron: "4f⁶ 6s²",
    group: 3,
    period: 6,
    category: "Lanthanide",
    mass: "150.36",
    electronegativity: 1.17,
    melting: 1345,
    boiling: 2067,
  },
  {
    number: 63,
    symbol: "Eu",
    name: { en: "Europium", ja: "ユウロピウム", zh: "铕" },
    electron: "4f⁷ 6s²",
    group: 3,
    period: 6,
    category: "Lanthanide",
    mass: "151.96",
    electronegativity: 1.2,
    melting: 1099,
    boiling: 1802,
  },
  {
    number: 64,
    symbol: "Gd",
    name: { en: "Gadolinium", ja: "ガドリニウム", zh: "钆" },
    electron: "4f⁷ 5d¹ 6s²",
    group: 3,
    period: 6,
    category: "Lanthanide",
    mass: "157.25",
    electronegativity: 1.2,
    melting: 1585,
    boiling: 3546,
  },
  {
    number: 65,
    symbol: "Tb",
    name: { en: "Terbium", ja: "テルビウム", zh: "铽" },
    electron: "4f⁹ 6s²",
    group: 3,
    period: 6,
    category: "Lanthanide",
    mass: "158.93",
    electronegativity: 1.2,
    melting: 1629,
    boiling: 3503,
  },
  {
    number: 66,
    symbol: "Dy",
    name: { en: "Dysprosium", ja: "ジスプロシウム", zh: "镝" },
    electron: "4f¹⁰ 6s²",
    group: 3,
    period: 6,
    category: "Lanthanide",
    mass: "162.50",
    electronegativity: 1.22,
    melting: 1680,
    boiling: 2840,
  },
  {
    number: 67,
    symbol: "Ho",
    name: { en: "Holmium", ja: "ホルミウム", zh: "钬" },
    electron: "4f¹¹ 6s²",
    group: 3,
    period: 6,
    category: "Lanthanide",
    mass: "164.93",
    electronegativity: 1.23,
    melting: 1734,
    boiling: 2993,
  },
  {
    number: 68,
    symbol: "Er",
    name: { en: "Erbium", ja: "エルビウム", zh: "铒" },
    electron: "4f¹² 6s²",
    group: 3,
    period: 6,
    category: "Lanthanide",
    mass: "167.26",
    electronegativity: 1.24,
    melting: 1802,
    boiling: 3141,
  },
  {
    number: 69,
    symbol: "Tm",
    name: { en: "Thulium", ja: "ツリウム", zh: "铥" },
    electron: "4f¹³ 6s²",
    group: 3,
    period: 6,
    category: "Lanthanide",
    mass: "168.93",
    electronegativity: 1.25,
    melting: 1818,
    boiling: 2223,
  },
  {
    number: 70,
    symbol: "Yb",
    name: { en: "Ytterbium", ja: "イッテルビウム", zh: "镱" },
    electron: "4f¹⁴ 6s²",
    group: 3,
    period: 6,
    category: "Lanthanide",
    mass: "173.05",
    electronegativity: 1.1,
    melting: 1097,
    boiling: 1469,
  },
  {
    number: 71,
    symbol: "Lu",
    name: { en: "Lutetium", ja: "ルテチウム", zh: "镥" },
    electron: "4f¹⁴ 5d¹ 6s²",
    group: 3,
    period: 6,
    category: "Lanthanide",
    mass: "174.97",
    electronegativity: 1.27,
    melting: 1925,
    boiling: 3675,
  },
  {
    number: 90,
    symbol: "Th",
    name: { en: "Thorium", ja: "トリウム", zh: "钍" },
    electron: "6d² 7s²",
    group: 3,
    period: 7,
    category: "Actinide",
    mass: "232.04",
    electronegativity: 1.3,
    melting: 2023,
    boiling: 5061,
  },
  {
    number: 91,
    symbol: "Pa",
    name: { en: "Protactinium", ja: "プロトアクチニウム", zh: "镤" },
    electron: "5f² 6d¹ 7s²",
    group: 3,
    period: 7,
    category: "Actinide",
    mass: "231.04",
    electronegativity: 1.5,
    melting: 1841,
    boiling: 4300,
  },
  {
    number: 92,
    symbol: "U",
    name: { en: "Uranium", ja: "ウラン", zh: "铀" },
    electron: "5f³ 6d¹ 7s²",
    group: 3,
    period: 7,
    category: "Actinide",
    mass: "238.03",
    electronegativity: 1.38,
    melting: 1405,
    boiling: 4404,
  },
  {
    number: 93,
    symbol: "Np",
    name: { en: "Neptunium", ja: "ネプツニウム", zh: "镎" },
    electron: "5f⁴ 6d¹ 7s²",
    group: 3,
    period: 7,
    category: "Actinide",
    mass: "(237)",
    electronegativity: 1.36,
    melting: 917,
    boiling: 4273,
  },
  {
    number: 94,
    symbol: "Pu",
    name: { en: "Plutonium", ja: "プルトニウム", zh: "钚" },
    electron: "5f⁶ 7s²",
    group: 3,
    period: 7,
    category: "Actinide",
    mass: "(244)",
    electronegativity: 1.28,
    melting: 912,
    boiling: 3501,
  },
  {
    number: 95,
    symbol: "Am",
    name: { en: "Americium", ja: "アメリシウム", zh: "镅" },
    electron: "5f⁷ 7s²",
    group: 3,
    period: 7,
    category: "Actinide",
    mass: "(243)",
    electronegativity: 1.13,
    melting: 1449,
    boiling: 2880,
  },
  {
    number: 96,
    symbol: "Cm",
    name: { en: "Curium", ja: "キュリウム", zh: "锔" },
    electron: "5f⁷ 6d¹ 7s²",
    group: 3,
    period: 7,
    category: "Actinide",
    mass: "(247)",
    electronegativity: 1.28,
    melting: 1613,
    boiling: 3383,
  },
  {
    number: 97,
    symbol: "Bk",
    name: { en: "Berkelium", ja: "バークリウム", zh: "锫" },
    electron: "5f⁹ 7s²",
    group: 3,
    period: 7,
    category: "Actinide",
    mass: "(247)",
    electronegativity: 1.3,
    melting: 1259,
    boiling: 2900,
  },
  {
    number: 98,
    symbol: "Cf",
    name: { en: "Californium", ja: "カリホルニウム", zh: "锎" },
    electron: "5f¹⁰ 7s²",
    group: 3,
    period: 7,
    category: "Actinide",
    mass: "(251)",
    electronegativity: 1.3,
    melting: 1173,
    boiling: 1743,
  },
  {
    number: 99,
    symbol: "Es",
    name: { en: "Einsteinium", ja: "アインスタイニウム", zh: "锿" },
    electron: "5f¹¹ 7s²",
    group: 3,
    period: 7,
    category: "Actinide",
    mass: "(252)",
    electronegativity: 1.3,
    melting: 1133,
    boiling: 1269,
  },
  {
    number: 100,
    symbol: "Fm",
    name: { en: "Fermium", ja: "フェルミウム", zh: "镄" },
    electron: "5f¹² 7s²",
    group: 3,
    period: 7,
    category: "Actinide",
    mass: "(257)",
    electronegativity: 1.3,
    melting: 1800,
    boiling: 1100,
  },
  {
    number: 101,
    symbol: "Md",
    name: { en: "Mendelevium", ja: "メンデレビウム", zh: "钔" },
    electron: "5f¹³ 7s²",
    group: 3,
    period: 7,
    category: "Actinide",
    mass: "(258)",
    electronegativity: 1.3,
    melting: 1100,
    boiling: 1100,
  },
  {
    number: 102,
    symbol: "No",
    name: { en: "Nobelium", ja: "ノーベリウム", zh: "锘" },
    electron: "5f¹⁴ 7s²",
    group: 3,
    period: 7,
    category: "Actinide",
    mass: "(259)",
    electronegativity: 1.3,
    melting: 1100,
    boiling: 1100,
  },
  {
    number: 103,
    symbol: "Lr",
    name: { en: "Lawrencium", ja: "ローレンシウム", zh: "铹" },
    electron: "5f¹⁴ 6d¹ 7s²",
    group: 3,
    period: 7,
    category: "Actinide",
    mass: "(266)",
    electronegativity: 1.3,
    melting: 1900,
    boiling: 1100,
  },
];
