# ignored by default: gitignore, hidden files, lock files

# [files]
# # Ignore specific files or directories
# extend-exclude = [
#   "pnpm-lock.yaml"
# ]

[default.extend-words]
# Ignore specific false positives
styl = "styl" # stylus
ba = "ba"
